apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-i8ze
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-i8ze
    app.kubernetes.io/part-of: tkrw-pr712-0075-0036-app
  name: devfile-sample-i8ze
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-i8ze
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-i8ze
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0036-tenant/tkrw-pr712-0075-0036-app/devfile-sample-i8ze@sha256:3a014b2d67dfbcf8d8a600eef1d848a5cb65dc2576cf4fc051f2099bb9fe9a11
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
